// <auto-generated/>
// Added by the Digi21.DigiNG NuGet package. Loads the Digi21.* assemblies from the Digi3D.AI installation
// folder, so that the application does not have to be copied there.
#nullable enable

namespace Digi21.DigiNG.Runtime
{
    internal static class Digi3DAssemblyResolver
    {
        // Overrides the installation folder read from the registry.
        private const string InstallDirVariable = "DIGI3D_INSTALLDIR";
        private const string RegistryKey = @"SOFTWARE\Digi21\Digi3D.NET\App\Configuration";

        private static readonly global::System.Lazy<string?> installDir = new(ReadInstallDir);

        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register()
        {
            if (global::System.OperatingSystem.IsWindows())
                global::System.Runtime.Loader.AssemblyLoadContext.Default.Resolving += Resolve;
        }

        [global::System.Runtime.Versioning.SupportedOSPlatform("windows")]
        private static global::System.Reflection.Assembly? Resolve(global::System.Runtime.Loader.AssemblyLoadContext context, global::System.Reflection.AssemblyName name)
        {
            if (name.Name is null || !name.Name.StartsWith("Digi21.", global::System.StringComparison.Ordinal))
                return null;

            var root = installDir.Value;
            if (root is null)
                return null;

            // Satellite assemblies are requested as "<Name>.resources" and live in a culture subfolder.
            var culture = name.CultureName ?? "";
            var isSatellite = culture.Length > 0 && name.Name.EndsWith(".resources", global::System.StringComparison.Ordinal);
            var baseName = isSatellite ? name.Name.Substring(0, name.Name.Length - ".resources".Length) : name.Name;
            var fileName = name.Name + ".dll";

            // Layout of the installation: <root>\<Name>\<version>\ or <root>\<Name>\<version>\lib\<tfm>\.
            foreach (var versionFolder in VersionFolders(global::System.IO.Path.Combine(root, baseName), name.Version))
            {
                var file = Find(versionFolder, culture, fileName, isSatellite);
                if (file is not null)
                    return context.LoadFromAssemblyPath(file);

                var lib = global::System.IO.Path.Combine(versionFolder, "lib");
                if (!global::System.IO.Directory.Exists(lib))
                    continue;

                foreach (var tfmFolder in global::System.IO.Directory.GetDirectories(lib))
                {
                    file = Find(tfmFolder, culture, fileName, isSatellite);
                    if (file is not null)
                        return context.LoadFromAssemblyPath(file);
                }
            }

            var rootFile = Find(root, culture, fileName, isSatellite);
            return rootFile is null ? null : context.LoadFromAssemblyPath(rootFile);
        }

        private static string? Find(string folder, string culture, string fileName, bool isSatellite)
        {
            var file = global::System.IO.Path.Combine(isSatellite ? global::System.IO.Path.Combine(folder, culture) : folder, fileName);
            return global::System.IO.File.Exists(file) ? file : null;
        }

        // The folder of the requested version first; then the other folders of the same major version, newest first.
        // Version 0.0.0.0 matches any folder: some published reference assemblies were built without a version.
        private static global::System.Collections.Generic.IEnumerable<string> VersionFolders(string assemblyFolder, global::System.Version? requested)
        {
            if (!global::System.IO.Directory.Exists(assemblyFolder))
                yield break;

            if (requested is not null && requested.Major == 0 && requested.Minor == 0 && requested.Build <= 0)
                requested = null;

            string? exact = null;
            if (requested is not null)
            {
                exact = global::System.IO.Path.Combine(assemblyFolder, $"{requested.Major}.{requested.Minor}.{(global::System.Math.Max(requested.Build, 0))}");
                if (global::System.IO.Directory.Exists(exact))
                    yield return exact;
            }

            var others = new global::System.Collections.Generic.List<(global::System.Version Version, string Folder)>();
            foreach (var folder in global::System.IO.Directory.GetDirectories(assemblyFolder))
            {
                if (global::System.Version.TryParse(global::System.IO.Path.GetFileName(folder), out var version)
                    && (requested is null || version.Major == requested.Major)
                    && !string.Equals(folder, exact, global::System.StringComparison.OrdinalIgnoreCase))
                    others.Add((version, folder));
            }

            others.Sort((a, b) => b.Version.CompareTo(a.Version));
            foreach (var other in others)
                yield return other.Folder;
        }

        [global::System.Runtime.Versioning.SupportedOSPlatform("windows")]
        private static string? ReadInstallDir()
        {
            var variable = global::System.Environment.GetEnvironmentVariable(InstallDirVariable);
            if (!string.IsNullOrEmpty(variable))
                return variable;

            try
            {
                using var baseKey = global::Microsoft.Win32.RegistryKey.OpenBaseKey(global::Microsoft.Win32.RegistryHive.LocalMachine, global::Microsoft.Win32.RegistryView.Registry64);
                using var key = baseKey.OpenSubKey(RegistryKey);
                return key?.GetValue("InstallDir") as string;
            }
            catch (global::System.Exception)
            {
                // Without access to the registry the assemblies are not resolved; the runtime reports FileNotFoundException.
                return null;
            }
        }
    }
}
